<a href="https://colab.research.google.com/github/AbanoubIbrahim98/Habak/blob/master/Abanoub.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
print("Hello Mr.Abanoub")

Hello Mr.Abanoub


In [12]:
!pip install numpy



In [35]:
x=np.my_array=([5, 9, 10, 18, 122, 14, 77])
print(x)
print(x[1:3])
print(x[2:7])


y=np.my_array=([[8, 8, 2, 11, 44, 99, 5],[8, 7, 1, 0, 22, 66, 8]])
print(y)
print(y[0:5])
print(y[0:3])

[5, 9, 10, 18, 122, 14, 77]
[9, 10]
[10, 18, 122, 14, 77]
[[8, 8, 2, 11, 44, 99, 5], [8, 7, 1, 0, 22, 66, 8]]
[[8, 8, 2, 11, 44, 99, 5], [8, 7, 1, 0, 22, 66, 8]]
[[8, 8, 2, 11, 44, 99, 5], [8, 7, 1, 0, 22, 66, 8]]


In [56]:

import numpy as np
Random=np.random.random((3,3))
print(Random)
print(Random[0:3])



import numpy as np
Zero= np.zeros([3,3])
print(Zero)

print("Yes")
import numpy as np 
Pop=np.ones([4,4])
print(Pop)

import numpy as np
Abanoub = np. full((5,5),8)
print(Abanoub)

import numpy as np
ident=np.eye(2,2)
print(ident)






[[0.68775384 0.05141151 0.88126503]
 [0.5591212  0.48116441 0.61807073]
 [0.15719942 0.89269504 0.77726943]]
[[0.68775384 0.05141151 0.88126503]
 [0.5591212  0.48116441 0.61807073]
 [0.15719942 0.89269504 0.77726943]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Yes
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]
[[1. 0.]
 [0. 1.]]


In [24]:
import numpy as np
x=np.array=([[5, 10, 10, 20, 25, 30],[25, 45, 60, 55, 80, 99]])
y=np.array=([[2, 3, 8, 9, 5, 7],[8, 4, 2, 1, 3, 6]])
print(x)
print(y)
print(np.add(x,y))
print(np.subtract(x,y))
print(np.divide(y,x))
print(np.multiply(x,y))
print(np.sqrt((x)))









[[5, 10, 10, 20, 25, 30], [25, 45, 60, 55, 80, 99]]
[[2, 3, 8, 9, 5, 7], [8, 4, 2, 1, 3, 6]]
[[  7  13  18  29  30  37]
 [ 33  49  62  56  83 105]]
[[ 3  7  2 11 20 23]
 [17 41 58 54 77 93]]
[[0.4        0.3        0.8        0.45       0.2        0.23333333]
 [0.32       0.08888889 0.03333333 0.01818182 0.0375     0.06060606]]
[[2.23606798 3.16227766 3.16227766 4.47213595 5.         5.47722558]
 [5.         6.70820393 7.74596669 7.41619849 8.94427191 9.94987437]]
[[ 10  30  80 180 125 210]
 [200 180 120  55 240 594]]


In [28]:
print(x)
x_new=np.sqrt(x)
y_new=np.divide(x,y)
print(x_new)
print(y_new)

z=np.multiply(x_new,y_new)
print(z)

[[5, 10, 10, 20, 25, 30], [25, 45, 60, 55, 80, 99]]
[[2.23606798 3.16227766 3.16227766 4.47213595 5.         5.47722558]
 [5.         6.70820393 7.74596669 7.41619849 8.94427191 9.94987437]]
[[ 2.5         3.33333333  1.25        2.22222222  5.          4.28571429]
 [ 3.125      11.25       30.         55.         26.66666667 16.5       ]]
[[  5.59016994  10.54092553   3.95284708   9.9380799   25.
   23.47382389]
 [ 15.625       75.46729424 232.37900077 407.89091679 238.5139176
  164.17292712]]


In [ ]:
import numpy as np
#Define an array of np's
My_Array= np.array=([10, 5, 9, 7])
print(My_Array)
print(type(My_Array))
print(My_Array.count)
print(My_Array[0])
My_Array[2]=80
print(My_Array[2])
print(My_Array[3])


In [43]:
import numpy as np
arr=np.array=([[5,6],[2, 4]])
v=np.array=([[5, 2],[3, 5, 9]])
print(v)


[[5, 2], [3, 5, 9]]
